/**
 * Writes supabase/seed.sql from the app's profile data, so the database and
 * the bundled cards never drift. Run: npm run seed:gen
 */
import { writeFileSync } from 'node:fs'
import { DECK, BONUS, MORE, COMETS, type Profile } from '../src/data/profiles.ts'
import { MATCHES } from '../src/data/matches.ts'

const q = (v: unknown) => (v == null ? 'null' : `'${String(v).replace(/'/g, "''")}'`)
const card = (p: Profile) => {
  const { id, name, age, sign, moon, rising, photo, alignsBack, founder, deal, ...rest } = p
  void id; void name; void age; void sign; void moon; void rising; void photo; void alignsBack; void founder; void deal
  return q(JSON.stringify(rest)) + '::jsonb'
}

const people = [...DECK, ...BONUS, ...MORE, ...COMETS]
const starter = new Map(MATCHES.filter((m) => m.day > 0).map((m) => [m.id, m]))
const row = (p: Pick<Profile, 'id' | 'name' | 'age' | 'sign' | 'moon' | 'rising' | 'photo' | 'alignsBack' | 'founder'>, cardSql: string) => {
  const s = starter.get(p.id)
  return `  (${[q(p.id), q(p.name), p.age, q(p.sign), q(p.moon), q(p.rising), q(p.photo), p.alignsBack ? 'true' : 'false', p.founder ?? 'null', cardSql,
    s ? s.day : 'null', s?.traded ? 'true' : 'false'].join(', ')})`
}
const rows = people.map((p) => row(p, card(p)))
// people you're already matched with who aren't in tonight's deck
for (const m of MATCHES) {
  if (people.some((p) => p.id === m.id)) continue
  rows.push(row({ id: m.id, name: m.name, age: m.age, sign: m.sign, moon: m.sign, rising: m.sign, photo: m.photo, alignsBack: false, founder: undefined },
    q(JSON.stringify({ serial: m.serial, pronoun: m.pronoun })) + '::jsonb'))
}

const sql = `-- Generated by app/scripts/gen-seed.ts. Do not edit by hand.
insert into public.profiles (id, name, age, sun, moon, rising, photo, aligns_back, founder, card, starter_day, starter_traded) values
${rows.join(',\n')}
on conflict (id) do update set
  name = excluded.name, age = excluded.age, sun = excluded.sun, moon = excluded.moon, rising = excluded.rising,
  photo = excluded.photo, aligns_back = excluded.aligns_back, founder = excluded.founder, card = excluded.card,
  starter_day = excluded.starter_day, starter_traded = excluded.starter_traded;
`
writeFileSync(new URL('../../supabase/seed.sql', import.meta.url), sql)
console.log(`seed.sql: ${rows.length} profiles, ${starter.size} starter matches`)
